/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // leftSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  leftSidebar: [
    'index',
    'automation-basics',
    'news',
    'contact',
    { // we define the category folders here so we do not need to add _category_.json files to each directory
      type: 'category',
      label: 'Dataverse Curation Automation: Beginner++ Study Basics',
      "link": {
        "type": "generated-index",
        "description": "If you are new to the Dataverse Curation Automation: Beginner++ data this is the place to start to learn more about the data that is available."
      },
      items: [

      ]
    },
  ],
};

export default sidebars;